version: '3.8'

services:
  seq:
    image: datalust/seq:2023.1
    container_name: seq
    ports:
      - "5340:80"
      - "5341:5341"
    environment:
      - ACCEPT_EULA=Y
      - SEQ_LICENSE=trial
    volumes:
      - ./seq:/data

  mysql-dev:
    image: mysql:8.0.25
    container_name: mysql-dev
    restart: always
    ports:
      - "3316:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: recipes
      MYSQL_USER: developer
      MYSQL_PASSWORD: developer
    volumes:
      - ./mysql-dev:/var/lib/mysql

  mysql-test:
    image: mysql:8.0.25
    container_name: mysql-test
    restart: always
    ports:
      - "3317:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: recipes
      MYSQL_USER: developer
      MYSQL_PASSWORD: developer
    volumes:
      - ./mysql-test:/var/lib/mysql
        
